# Generated by Django 3.0.3 on 2020-02-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weight', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PizzaComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('pizza_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_app.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dough', models.CharField(choices=[('thin', 'Thin dough (6 mm)'), ('thick', 'Thick dough (1 cm)')], default='thin', max_length=10)),
                ('sauce', models.CharField(choices=[('marinara', 'Marinara sauce'), ('bbq', 'Barbeque sauce')], default='marinara', max_length=20)),
                ('toppings', models.ManyToManyField(to='pizza_app.PizzaComponent')),
            ],
        ),
    ]
